export default {
  SAVE_EMAIL_PASSWORD: '@USER/SAVE_EMAIL_PASSWORD',
  SAVE_LOCATION: '@USER/SAVE_LOCATION',
  SAVE_NAME: '@USER/SAVE_NAME',
  STORE_USER_REQUEST: '@USER/STORE_USER_REQUEST',
  STORE_USER_SUCCESS: '@USER/STORE_USER_SUCCESS',
  SEARCH_ADDRESS_REQUEST: '@USER/SEARCH_ADDRESS_REQUEST',
  SEARCH_ADDRESS_SUCCESS: '@USER/SEARCH_ADDRESS_SUCCESS',
  SEARCH_LAT_LONG_REQUEST: '@USER/SEARCH_LAT_LONG_REQUEST',
  SEARCH_LAT_LONG_SUCCESS: '@USER/SEARCH_LAT_LONG_SUCCESS',
  PROCEDURE_FAIL: '@USER/PROCEDURE_FAIL',
};
