export default {
  INDEX_MEDS_REQUEST: '@MEDS/INDEX_MEDS_REQUEST',
  INDEX_MEDS_SUCCESS: '@MEDS/INDEX_MEDS_SUCCESS',
  STORE_MEDS_REQUEST: '@MEDS/STORE_MEDS_REQUEST',
  STORE_MEDS_SUCCESS: '@MEDS/STORE_MEDS_SUCCESS',
  RESET_REGISTERED: '@MEDS/RESET_REGISTERED',
  RESET_DATA: '@MEDS/RESET_DATA',
  SET_SELECT_MED: '@MEDS/SET_SELECT_MED',
  PROCEDURE_ERROR: '@MEDS/PROCEDURE_ERROR',
};
