export default {
  INDEX_VACINATION_REQUEST: '@VACINATION/INDEX_VACINATION_REQUEST',
  INDEX_VACINATION_SUCCESS: '@VACINATION/INDEX_VACINATION_SUCCESS',
  SET_PAGE: '@VACINATION/SET_PAGE',
  PROCEDURE_FAILURE: '@VACINATION/PROCEDURE_FAILURE',
};
