export default {
  SIGN_IN_REQUEST: '@AUTH/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: '@AUTH/SIGN_IN_SUCCESS',
  PROCEDURE_FAIL: '@AUTH/PROCEDURE_FAIL',
  SIGN_UP_SUCCESS: '@AUTH/SIGN_UP_SUCCESS',
  SIGN_OUT: '@AUTH/SIGN_OUT',
};
